cmake_minimum_required(VERSION 3.13)

if (NOT HOUDINI_USER_PATH)
    if (PLD_WINDOWS)
        set(HOUDINI_USER_PATH "$ENV{HOMEDRIVE}$ENV{HOMEPATH}/Documents/houdini${Houdini_VERSION_MAJOR}.${Houdini_VERSION_MINOR}")
    else ()
        set(HOUDINI_USER_PATH "$ENV{HOME}/houdini${Houdini_VERSION_MAJOR}.${Houdini_VERSION_MINOR}")
    endif ()
endif ()

set(HOUDINI_DSO_PATH "${HOUDINI_USER_PATH}/${HOUDINI_RELATIVE_DSO_PATH}")
set(HOUDINI_ICON_PATH "${HOUDINI_USER_PATH}/${HOUDINI_RELATIVE_ICON_PATH}")
set(HOUDINI_PACKAGES_PATH "${HOUDINI_USER_PATH}/${HOUDINI_RELATIVE_PACKAGES_PATH}")

message(STATUS "HOUDINI_DSO_PATH = ${HOUDINI_DSO_PATH}")
message(STATUS "HOUDINI_ICON_PATH = ${HOUDINI_ICON_PATH}")
message(STATUS "HOUDINI_PACKAGES_PATH = ${HOUDINI_PACKAGES_PATH}")

if (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
    set(CMAKE_INSTALL_PREFIX "${HOUDINI_USER_PATH}" CACHE PATH "default install path" FORCE)
    message(STATUS "Set default install prefix: ${CMAKE_INSTALL_PREFIX}")
endif ()
